import urllib.request, json

URL = "https://rrbvghxmnimusfyqixau.supabase.co/rest/v1/fiches"
KEY = "sb_publishable_k0nVhKHWUT5kBW9xBNpLkA_AKam7uBa"
HEADERS = {
    "apikey": KEY,
    "Authorization": "Bearer " + KEY,
    "Content-Type": "application/json",
    "Prefer": "return=minimal"
}

fiches = [
    "Élagage Valence",
    "Élagage & Abattage Millau",
    "Rouen Nettoyage",
    "Renovation Toiture Toulouse",
    "Renovation Toiture Lyon",
    "Reparation Toiture Nice",
    "Rénovation Toiture Cherbourg",
    "Rénovation Toiture La Rochelle",
    "Rénovation Toiture Brest",
    "Renovation Toiture Rennes",
    "Nettoyage Cherbourg",
    "Nettoyage La Rochelle",
    "Mr Emondeur",
    "Étanchéité Bordeaux",
    "Depannage Remorquage Reims",
    "Débarras Tours",
    "Élagage Plan De Cuques",
    "Élagage Courdimanche",
    "Paysagiste Vauréal",
    "Élagage Franconville",
    "Élagage Allauch",
    "Élagage Lens",
    "Élagage Cassis",
    "Élagage Saint-Cyr-sur-Mer",
    "Élagage Villeurbanne",
    "Élagage Rouen",
    "Élagage Tourcoing",
    "Élagage Amiens",
    "Élagage et Abattage - Pau 64",
    "Élagage Paris",
    "Élagage Avignon",
    "Élagage Dunkerque",
    "Élagage Toulouse",
    "Elagage Villeneuve d'Ascq",
    "Elagage Colmar",
    "Renovation Toiture Rouen",
    "Élagage Metz",
    "Besançon Elagage",
    "Elagage Namur",
    "Élagage Cannes",
    "Élagage Abattage Cannes",
    "Elagage Mulhouse",
    "Élagage Var",
    "Elagage Luxembourg",
    "Elagage Bruxelles",
    "Élagage Abattage Jardinage Brest - Paysagiste 29",
    "Élagage Abattage Dessouchage - Troyes Aube",
    "Elagage & Abattage Reims",
    "Elagage Reims",
    "Elagage et Abattage - Rennes 35",
    "Élagage Chambéry",
    "Élagage Abattage Dessouchage Toulon - Paysagiste 83",
    "Élagage Abattage Jardinage Grenoble - Paysagiste 38",
    "Elagage Abattage et Taille de Haies - Lorient 56",
    "Élagage Clermont-Ferrand",
    "Élagage Bourg-en-Bresse",
    "Elagage & Abattage Martigues",
    "Élagage Montpellier",
    "Élagage Nice",
    "Terrassement Saint Denis",
    "Artisan Couvreur Nantes",
    "Couvreur Caen",
    "Couvreur Rénovation Réparation toiture - Le Mans 72",
    "Élagage, Abattage & Taille de Haie - Angers 49",
    "Service express élagage abattage pro lyon",
    "Elagage, Abattage & Dessouchage - La Ciotat 13",
    "Elagage Laval 53",
    "Marseille Élagage",
    "Paysagiste Caen",
    "Artisan du Paysage Aubagne",
    "Paysagiste Val D'Oise",
    "Ravalement Angers",
    "Elagage Merignac",
    "Paysagiste Angers",
    "Paysagiste Toulouse",
    "Terrassement Dijon",
    "Élagage & Abattage Jardinage Rhône - Paysagiste Lyon 69",
    "Elagage Abattage & Taille de Haies Tarn",
    "Élagage Aveyron",
    "Macon Colmar",
    "Couvreur Pyrénées-Orientales",
    "Couvreur Haut-Rhin",
    "Couvreur Charente-Maritime",
    "Couvreur Hérault",
    "Nettoyage Hérault",
    "Élagage, Abattage, Jardinage Compiègne - Paysagiste Oise 60",
    "Élagage & Abattage, Taille de Haie - Béziers 34",
    "Nettoyage Toiture, Terrasse & Façade Toulouse - Démoussage 31",
    "Nettoyage Toiture, Terrasse & Façade Strasbourg - Démoussage Alsace",
    "Nettoyage Toiture, Terrasse & Façade Lille - Démoussage Nord",
    "Nettoyage Toiture, Terrasse & Façade - Dijon 21",
    "Nettoyage Toiture, Terrasse & Façade Pau - Démoussage 64",
    "Nettoyage Toiture, Terrasse & Façade Brest - Démoussage 29",
    "Nettoyage Toiture, Terrasse & Façade La Rochelle - Démoussage 17",
    "Nettoyage Toiture, Terrasse & Façade Cherbourg - Démoussage 50",
    "Nettoyage Toiture, Terrasse & Façade Mulhouse - Démoussage 68",
    "Nettoyage Toiture, Terrasse & Façade Amiens Somme",
    "Nettoyage Toiture, Terrasse & Façade - Somme 80",
    "Nettoyage Toiture, Terrasse & Façade Belfort - Démoussage 90",
    "Nettoyage Toiture, Terrasse & Façade - Toulon 83",
    "Nettoyage Toiture, Terrasse & Façade Montpellier - Démoussage 34",
    "Nettoyage Toiture, Terrasse & Façade - Aix-en-Provence 13",
    "Nettoyage Toiture, Terrasse & Façade Nîmes - Démoussage 30",
    "Nettoyage Toiture, Terrasse & Façade Le Havre - Démoussage 76",
    "Nettoyage Vosges",
    "Nettoyage Morbihan",
    "Nettoyage Toiture, Terrasse & Façade Morbihan - Démoussage 56",
    "Infiltration Fuite Etancheite Toiture rouen",
    "Nettoyage Toiture, Terrasse & Façade Bordeaux - Démoussage Gironde",
    "Élagage Abattage & Taille de Haies Vendée",
    "Elagage & Abattage Isère",
    "Elagage & Abattage Alpes-Maritmes",
    "Elagage & Abattage Gers",
    "Elagage & Abattage Charente",
    "Elagage & Abattage Vosges",
    "Elagage & Abattage Bas-Rhin",
    "Elagage Essonne 91",
    "Elagage & Abattage - Seine et Marne 77",
    "Elagage & Abattage Orne",
    "Elagage, Abattage & Taille de Haie - Ardennes",
    "Elagage & Abattage Tarn",
    "Elagage & Abattage Landes",
    "Elagage & Abattage Lot (Cahors)",
    "Elagage & Abattage Aude",
    "Elagage & Abattage Oise",
    "Elagage & Abattage Saône et loire",
    "Elagage & Abattage Pyrénées Orientales",
    "Elagage Grenoble",
    "Élagage Genève",
    "Élagage et Abattage, Pyrénées-Atlantiques 64",
    "Elagage Saint-Denis",
    "Elagage Fontenay-sous-Bois",
    "Elagage Cachan",
    "Elagage Ivry-sur-Seine",
    "Elagage Alfortville",
    "Elagage Maisons-Alfort",
    "Elagage Arcueil",
    "Elagage Gentilly",
    "Elagage Bagnolet",
    "Elagage Val-d'Oise",
    "Elagage Joinville-le-Pont",
    "Elagage Thiais",
    "Elagage Issy-les-Moulineaux",
    "Elagage Meudon",
    "Elagage Clamart",
    "Elagage Montrouge",
    "Elagage Vanves",
    "Elagage Brunoy",
    "Elagage Le Perreux-sur-Marne",
    "Elagage Noisy-le-Sec",
    "Elagage Vincennes",
    "Elagage Saint-Ouen",
    "Elagage Aubervilliers",
    "Elagage Noisy-le-Grand",
    "Elagage Les Lilas",
    "Elagage Drancy",
    "Elagage Pantin",
    "Elagage Sevran",
    "Elagage Bondy",
    "Elagage La Courneuve",
    "Elagage Bobigny",
    "Elagage Montreuil",
    "Elagage Romainville",
]

ok = 0
errors = 0
for nom in fiches:
    data = json.dumps({"nom": nom}).encode("utf-8")
    req = urllib.request.Request(URL, data=data, headers=HEADERS, method="POST")
    try:
        with urllib.request.urlopen(req) as resp:
            print(f"✅ {nom}")
            ok += 1
    except Exception as e:
        print(f"❌ {nom} : {e}")
        errors += 1

print(f"\n=== {ok} insérées, {errors} erreurs ===")
