/**
 * debug/snapshots-t40.js
 * Référence déterministe de buildDallePromptV2 — générée le 2026-07-15 (Phase 0).
 *
 * Méthode de comparaison (T40) :
 *   1. Comparaison principale : stableJson (sérialisation déterministe, clés triées récursivement)
 *   2. Résumé : hash polynomial 32 bits sur stableJson
 *
 * NE PAS MODIFIER MANUELLEMENT.
 * Régénérer via _regenerateT40Snapshots() après validation d'un changement intentionnel.
 *
 * Chaque entrée contient :
 *   id            — identifiant lisible
 *   input         — row passé à buildDallePromptV2 (hors nb/fiche/meteo/images)
 *   expectedPayload — objet complet retourné (parsé)
 *   stableJson    — sérialisation déterministe pour comparaison exacte
 *   hash          — hash32(stableJson), résumé rapide
 */

// Snapshots Phase 0 — générés le 2026-07-15
const T40_SNAPSHOTS = [
  {
    id: 'toiture-nettoyage',
    input: { metier: 'toiture', travaux: 'nettoyage gouttières', contexte: 'maison', etat: 'encours', ville: 'Paris' },
    expectedPayload: {"_match_score":20,"_matched_category":"couverture","_matched_key":"toiture","_matched_service":"nettoyage gouttières","architecture":"classic Haussmann-style stone buildings with zinc rooftops and wrought-iron balconies","camera_position":"standing in the driveway or garden, 3–6 m from house, looking up at roof","contexte":"maison","exclude":["safety harnesses","helmets","scaffolding tools","workers","people"],"framing":{"background":"opposite roof slope still tiled, sky, chimney tops","foreground":"organised pile of old tiles on driveway, mortar chips nearby","midground":"roof half stripped — one slope bare showing wooden battens, pallet of new tiles staged to the side","work_pct":55},"light":"pale urban Île-de-France sky and diffuse city light","location":"Paris, France","no_people":true,"photo_defects":["overexposure on pale sky bleaching the top third","JPEG compression artifacts on rough tile texture"],"photo_goal":"work-progress documentation by French contractor, cheap Android smartphone","roadside_context":null,"setting":"exterior","site_debris":"old tiles stacked on driveway, mortar dust and a few broken fragments — an active but organised site","state":"Halfway through. Half the roof is stripped to the battens. The other half remains. A pallet of new tiles is staged. Active professional work.","state_level":"encours","work_type":"roof renovation on a residential house"},
    stableJson: '{"_match_score":20,"_matched_category":"couverture","_matched_key":"toiture","_matched_service":"nettoyage gouttières","architecture":"classic Haussmann-style stone buildings with zinc rooftops and wrought-iron balconies","camera_position":"standing in the driveway or garden, 3–6 m from house, looking up at roof","contexte":"maison","exclude":["safety harnesses","helmets","scaffolding tools","workers","people"],"framing":{"background":"opposite roof slope still tiled, sky, chimney tops","foreground":"organised pile of old tiles on driveway, mortar chips nearby","midground":"roof half stripped — one slope bare showing wooden battens, pallet of new tiles staged to the side","work_pct":55},"light":"pale urban Île-de-France sky and diffuse city light","location":"Paris, France","no_people":true,"photo_defects":["overexposure on pale sky bleaching the top third","JPEG compression artifacts on rough tile texture"],"photo_goal":"work-progress documentation by French contractor, cheap Android smartphone","roadside_context":null,"setting":"exterior","site_debris":"old tiles stacked on driveway, mortar dust and a few broken fragments — an active but organised site","state":"Halfway through. Half the roof is stripped to the battens. The other half remains. A pallet of new tiles is staged. Active professional work.","state_level":"encours","work_type":"roof renovation on a residential house"}',
    hash: 2455936913,
  },
  {
    id: 'toiture-tuiles',
    input: { metier: 'toiture', travaux: 'Remplacement de tuiles', contexte: 'maison', etat: 'encours', ville: 'Paris' },
    expectedPayload: {"_match_score":20,"_matched_category":"couverture","_matched_key":"toiture","_matched_service":"Remplacement de tuiles","architecture":"classic Haussmann-style stone buildings with zinc rooftops and wrought-iron balconies","camera_position":"standing in the driveway or garden, 3–6 m from house, looking up at roof","contexte":"maison","exclude":["safety harnesses","helmets","scaffolding tools","workers","people"],"framing":{"background":"opposite roof slope still tiled, sky, chimney tops","foreground":"organised pile of old tiles on driveway, mortar chips nearby","midground":"roof half stripped — one slope bare showing wooden battens, pallet of new tiles staged to the side","work_pct":55},"light":"pale urban Île-de-France sky and diffuse city light","location":"Paris, France","no_people":true,"photo_defects":["overexposure on pale sky bleaching the top third","JPEG compression artifacts on rough tile texture"],"photo_goal":"work-progress documentation by French contractor, cheap Android smartphone","roadside_context":null,"setting":"exterior","site_debris":"old tiles stacked on driveway, mortar dust and a few broken fragments — an active but organised site","state":"Halfway through. Half the roof is stripped to the battens. The other half remains. A pallet of new tiles is staged. Active professional work.","state_level":"encours","work_type":"roof renovation on a residential house"},
    stableJson: '{"_match_score":20,"_matched_category":"couverture","_matched_key":"toiture","_matched_service":"Remplacement de tuiles","architecture":"classic Haussmann-style stone buildings with zinc rooftops and wrought-iron balconies","camera_position":"standing in the driveway or garden, 3–6 m from house, looking up at roof","contexte":"maison","exclude":["safety harnesses","helmets","scaffolding tools","workers","people"],"framing":{"background":"opposite roof slope still tiled, sky, chimney tops","foreground":"organised pile of old tiles on driveway, mortar chips nearby","midground":"roof half stripped — one slope bare showing wooden battens, pallet of new tiles staged to the side","work_pct":55},"light":"pale urban Île-de-France sky and diffuse city light","location":"Paris, France","no_people":true,"photo_defects":["overexposure on pale sky bleaching the top third","JPEG compression artifacts on rough tile texture"],"photo_goal":"work-progress documentation by French contractor, cheap Android smartphone","roadside_context":null,"setting":"exterior","site_debris":"old tiles stacked on driveway, mortar dust and a few broken fragments — an active but organised site","state":"Halfway through. Half the roof is stripped to the battens. The other half remains. A pallet of new tiles is staged. Active professional work.","state_level":"encours","work_type":"roof renovation on a residential house"}',
    hash: 2385610455,
  },
  {
    id: 'plomberie-debouchage',
    input: { metier: 'plomberie', travaux: 'Débouchage canalisation', contexte: 'appartement', etat: 'encours', ville: 'Paris' },
    expectedPayload: {"_match_score":20,"_matched_category":"plomberie","_matched_key":"plomberie","_matched_service":"Débouchage canalisation","architecture":"classic Haussmann-style stone buildings with zinc rooftops and wrought-iron balconies","camera_position":"crouching or kneeling, 1–2 m from the pipes or open wall cavity","contexte":"appartement","exclude":["pipe wrenches","tools","buckets","cleaning supplies","workers","people"],"framing":{"background":"white wall, some tiles, window or door","foreground":"copper pipes partially installed, visible fittings and PTFE tape on the floor","midground":"new pipe run in progress — some sections soldered, others still raw","work_pct":60},"light":"natural daylight from window","location":"Paris, France","no_people":true,"photo_defects":["low ambient light with slight sensor noise","flat artificial ceiling light only — no natural light"],"photo_goal":"work-progress documentation by French contractor, cheap Android smartphone","roadside_context":null,"setting":"interior","site_debris":"pipe offcuts, PTFE tape scraps and fitting packaging on the floor","state":"Plumbing installation is underway. New copper pipes are being run. Some sections are soldered, others still open. The job is progressing.","state_level":"encours","work_type":"plumbing renovation inside a residential property"},
    stableJson: '{"_match_score":20,"_matched_category":"plomberie","_matched_key":"plomberie","_matched_service":"Débouchage canalisation","architecture":"classic Haussmann-style stone buildings with zinc rooftops and wrought-iron balconies","camera_position":"crouching or kneeling, 1–2 m from the pipes or open wall cavity","contexte":"appartement","exclude":["pipe wrenches","tools","buckets","cleaning supplies","workers","people"],"framing":{"background":"white wall, some tiles, window or door","foreground":"copper pipes partially installed, visible fittings and PTFE tape on the floor","midground":"new pipe run in progress — some sections soldered, others still raw","work_pct":60},"light":"natural daylight from window","location":"Paris, France","no_people":true,"photo_defects":["low ambient light with slight sensor noise","flat artificial ceiling light only — no natural light"],"photo_goal":"work-progress documentation by French contractor, cheap Android smartphone","roadside_context":null,"setting":"interior","site_debris":"pipe offcuts, PTFE tape scraps and fitting packaging on the floor","state":"Plumbing installation is underway. New copper pipes are being run. Some sections are soldered, others still open. The job is progressing.","state_level":"encours","work_type":"plumbing renovation inside a residential property"}',
    hash: 1029236932,
  },
  {
    id: 'plomberie-fuite',
    input: { metier: 'plomberie', travaux: "Fuite d'eau", contexte: 'maison', etat: 'debut', ville: 'Paris' },
    expectedPayload: {"_match_score":20,"_matched_category":"plomberie","_matched_key":"plomberie","_matched_service":"Fuite d'eau","architecture":"classic Haussmann-style stone buildings with zinc rooftops and wrought-iron balconies","camera_position":"crouching or kneeling, 1–2 m from the pipes or open wall cavity","contexte":"maison","exclude":["pipe wrenches","tools","buckets","cleaning supplies","workers","people"],"framing":{"background":"white bathroom wall, existing tiles","foreground":"old pipe section removed, wall cavity open, fresh drill dust on floor","midground":"exposed wall showing old pipe stub and new pipe start being positioned","work_pct":50},"light":"natural daylight from window","location":"Paris, France","no_people":true,"photo_defects":["low ambient light with slight sensor noise","flat artificial ceiling light only — no natural light"],"photo_goal":"work-progress documentation by French contractor, cheap Android smartphone","roadside_context":null,"setting":"interior","site_debris":"pipe offcuts, drill dust and small plaster fragments near the wall opening","state":"Work has just started. Old pipes are being removed. The wall is open. New pipe routing is being planned.","state_level":"debut","work_type":"plumbing renovation inside a residential property"},
    stableJson: '{"_match_score":20,"_matched_category":"plomberie","_matched_key":"plomberie","_matched_service":"Fuite d\'eau","architecture":"classic Haussmann-style stone buildings with zinc rooftops and wrought-iron balconies","camera_position":"crouching or kneeling, 1–2 m from the pipes or open wall cavity","contexte":"maison","exclude":["pipe wrenches","tools","buckets","cleaning supplies","workers","people"],"framing":{"background":"white bathroom wall, existing tiles","foreground":"old pipe section removed, wall cavity open, fresh drill dust on floor","midground":"exposed wall showing old pipe stub and new pipe start being positioned","work_pct":50},"light":"natural daylight from window","location":"Paris, France","no_people":true,"photo_defects":["low ambient light with slight sensor noise","flat artificial ceiling light only — no natural light"],"photo_goal":"work-progress documentation by French contractor, cheap Android smartphone","roadside_context":null,"setting":"interior","site_debris":"pipe offcuts, drill dust and small plaster fragments near the wall opening","state":"Work has just started. Old pipes are being removed. The wall is open. New pipe routing is being planned.","state_level":"debut","work_type":"plumbing renovation inside a residential property"}',
    hash: 1088613504,
  },
  {
    id: 'electricite-normes',
    input: { metier: 'électricité', travaux: 'Mise aux normes électrique', contexte: 'appartement', etat: 'encours', ville: 'Paris' },
    expectedPayload: {"_match_score":20,"_matched_category":"électricité","_matched_key":"électricité","_matched_service":"Mise aux normes électrique","architecture":"classic Haussmann-style stone buildings with zinc rooftops and wrought-iron balconies","camera_position":"standing or crouching, 1–2 m from open wall cavity or distribution board","contexte":"appartement","exclude":["screwdrivers","wire strippers","safety equipment","workers","people"],"framing":{"background":"bare plaster wall, door frame","foreground":"cable offcuts and junction box scraps on the bare floor","midground":"cables installed in channels, junction boxes fitted, outlets in progress","work_pct":55},"light":"natural daylight from window","location":"Paris, France","no_people":true,"photo_defects":["mixed ceiling lamp and window light causing uneven exposure","JPEG compression noise in dark cable areas"],"photo_goal":"work-progress documentation by French contractor, cheap Android smartphone","roadside_context":null,"setting":"interior","site_debris":"cable offcuts, conduit pieces and screw packaging on the floor","state":"Cables are in and junction boxes are fitted. Outlet positions are being confirmed. The work is clear and progressing.","state_level":"encours","work_type":"electrical installation inside a residential property"},
    stableJson: '{"_match_score":20,"_matched_category":"électricité","_matched_key":"électricité","_matched_service":"Mise aux normes électrique","architecture":"classic Haussmann-style stone buildings with zinc rooftops and wrought-iron balconies","camera_position":"standing or crouching, 1–2 m from open wall cavity or distribution board","contexte":"appartement","exclude":["screwdrivers","wire strippers","safety equipment","workers","people"],"framing":{"background":"bare plaster wall, door frame","foreground":"cable offcuts and junction box scraps on the bare floor","midground":"cables installed in channels, junction boxes fitted, outlets in progress","work_pct":55},"light":"natural daylight from window","location":"Paris, France","no_people":true,"photo_defects":["mixed ceiling lamp and window light causing uneven exposure","JPEG compression noise in dark cable areas"],"photo_goal":"work-progress documentation by French contractor, cheap Android smartphone","roadside_context":null,"setting":"interior","site_debris":"cable offcuts, conduit pieces and screw packaging on the floor","state":"Cables are in and junction boxes are fitted. Outlet positions are being confirmed. The work is clear and progressing.","state_level":"encours","work_type":"electrical installation inside a residential property"}',
    hash: 1746687025,
  },
  {
    id: 'depannage-auto-batterie',
    input: { metier: 'depannage_auto', travaux: 'batterie à plat', contexte: 'domicile', etat: 'encours', ville: 'Paris' },
    expectedPayload: {"_match_score":20,"_matched_category":"dépannage auto","_matched_key":"depannage_auto","_matched_service":"batterie à plat","architecture":"classic Haussmann-style stone buildings with zinc rooftops and wrought-iron balconies","camera_position":"standing 3–5 m from the car, eye level, showing vehicle and roadside context","contexte":"domicile","exclude":["readable licence plates","brand logos","workers","people","driver"],"framing":{"background":"road, fence or hedge, distant vehicles","foreground":"car bonnet open, engine bay visible, jump cables or diagnostic equipment nearby","midground":"van open with equipment visible, technician at the front of the car","work_pct":55},"light":"pale urban Île-de-France sky and diffuse city light","location":"Paris, France","no_people":true,"photo_defects":["overexposure from bright sky against dark car bodywork","slight motion blur from passing traffic in background"],"photo_goal":"work-progress documentation by French contractor, cheap Android smartphone","roadside_context":"parked on private residential property — driveway, garage forecourt, or enclosed courtyard. A gate, wall, or house facade must be visible in the background. No road markings, no public pavement, no carriageway in the scene.","setting":"exterior","site_debris":"jump cable on the road near the battery, warning vest placed on car roof","state":"Diagnosis underway. Bonnet open. Jump cables or tools connecting the vehicles.","state_level":"encours","work_type":"roadside vehicle breakdown assistance and recovery"},
    stableJson: '{"_match_score":20,"_matched_category":"dépannage auto","_matched_key":"depannage_auto","_matched_service":"batterie à plat","architecture":"classic Haussmann-style stone buildings with zinc rooftops and wrought-iron balconies","camera_position":"standing 3–5 m from the car, eye level, showing vehicle and roadside context","contexte":"domicile","exclude":["readable licence plates","brand logos","workers","people","driver"],"framing":{"background":"road, fence or hedge, distant vehicles","foreground":"car bonnet open, engine bay visible, jump cables or diagnostic equipment nearby","midground":"van open with equipment visible, technician at the front of the car","work_pct":55},"light":"pale urban Île-de-France sky and diffuse city light","location":"Paris, France","no_people":true,"photo_defects":["overexposure from bright sky against dark car bodywork","slight motion blur from passing traffic in background"],"photo_goal":"work-progress documentation by French contractor, cheap Android smartphone","roadside_context":"parked on private residential property — driveway, garage forecourt, or enclosed courtyard. A gate, wall, or house facade must be visible in the background. No road markings, no public pavement, no carriageway in the scene.","setting":"exterior","site_debris":"jump cable on the road near the battery, warning vest placed on car roof","state":"Diagnosis underway. Bonnet open. Jump cables or tools connecting the vehicles.","state_level":"encours","work_type":"roadside vehicle breakdown assistance and recovery"}',
    hash: 919780194,
  },
  {
    id: 'peinture-interieure',
    input: { metier: 'peinture', travaux: 'Peinture intérieure', contexte: 'appartement', etat: 'encours', ville: 'Paris' },
    expectedPayload: {"_match_score":20,"_matched_category":"peinture","_matched_key":"peinture","_matched_service":"Peinture intérieure","architecture":"ordinary occupied French residential interior — plaster walls, skirting boards, standard doors and windows","camera_position":"standing naturally inside the room near the doorway, smartphone held at chest height — casual handheld angle","contexte":"appartement","exclude":["exterior facade","street","garden","pavement","scaffolding","roof","open sky","outdoor architecture","house exterior","ladders","paint rollers","brushes","buckets","workers","people"],"framing":{"background":"opposite interior wall, ordinary room depth with skirting board, door frame or window frame — no outdoor elements","foreground":"protected floor edge with a canvas drop cloth, paint tray or part of the doorway frame","midground":"wall or ceiling currently being painted — masking tape at the edges, fresh colour against the old","work_pct":55},"light":"soft natural daylight entering from the room window, supplemented by ordinary indoor ambient ceiling light","location":"Paris, France","no_people":true,"photo_defects":["flat overcast light causing slight overexposure on white painted surface","chromatic aberration on the sharp painted edge between old and new colour"],"photo_goal":"work-progress documentation by French contractor, cheap Android smartphone","roadside_context":null,"setting":"interior","site_debris":"drop cloths on ground with paint drips, empty paint cans stacked at wall base","state":"Painting is underway. Half the facade shows the new colour. The line between fresh and old paint is clearly visible.","state_level":"encours","work_type":"exterior facade painting on a residential house"},
    stableJson: '{"_match_score":20,"_matched_category":"peinture","_matched_key":"peinture","_matched_service":"Peinture intérieure","architecture":"ordinary occupied French residential interior — plaster walls, skirting boards, standard doors and windows","camera_position":"standing naturally inside the room near the doorway, smartphone held at chest height — casual handheld angle","contexte":"appartement","exclude":["exterior facade","street","garden","pavement","scaffolding","roof","open sky","outdoor architecture","house exterior","ladders","paint rollers","brushes","buckets","workers","people"],"framing":{"background":"opposite interior wall, ordinary room depth with skirting board, door frame or window frame — no outdoor elements","foreground":"protected floor edge with a canvas drop cloth, paint tray or part of the doorway frame","midground":"wall or ceiling currently being painted — masking tape at the edges, fresh colour against the old","work_pct":55},"light":"soft natural daylight entering from the room window, supplemented by ordinary indoor ambient ceiling light","location":"Paris, France","no_people":true,"photo_defects":["flat overcast light causing slight overexposure on white painted surface","chromatic aberration on the sharp painted edge between old and new colour"],"photo_goal":"work-progress documentation by French contractor, cheap Android smartphone","roadside_context":null,"setting":"interior","site_debris":"drop cloths on ground with paint drips, empty paint cans stacked at wall base","state":"Painting is underway. Half the facade shows the new colour. The line between fresh and old paint is clearly visible.","state_level":"encours","work_type":"exterior facade painting on a residential house"}',
    hash: 3792538061,
  },
  {
    id: 'maconnerie-enduit',
    input: { metier: 'maçonnerie', travaux: 'Réfection enduit façade', contexte: 'maison', etat: 'encours', ville: 'Paris' },
    expectedPayload: {"_match_score":20,"_matched_category":"maçonnerie","_matched_key":"maçonnerie","_matched_service":"Réfection enduit façade","architecture":"classic Haussmann-style stone buildings with zinc rooftops and wrought-iron balconies","camera_position":"standing 2–4 m from the wall, straight-on or slight diagonal, eye level","contexte":"maison","exclude":["trowels","mixing tools","wheelbarrows","safety equipment","workers","people"],"framing":{"background":"adjacent existing structure or garden","foreground":"concrete blocks and mortar debris at the base, sand pile nearby","midground":"half-height wall under construction — fresh dark mortar joints clearly visible, blocks not yet fully set","work_pct":55},"light":"pale urban Île-de-France sky and diffuse city light","location":"Paris, France","no_people":true,"photo_defects":["flat midday light casting short even shadows","lens barrel distortion on straight wall lines"],"photo_goal":"work-progress documentation by French contractor, cheap Android smartphone","roadside_context":null,"setting":"exterior","site_debris":"mortar splashes on ground, block dust, open cement bags nearby","state":"The wall is at mid-height. Fresh mortar joints are visible. Blocks are stacked and ready. An active organised site.","state_level":"encours","work_type":"masonry work at a residential property"},
    stableJson: '{"_match_score":20,"_matched_category":"maçonnerie","_matched_key":"maçonnerie","_matched_service":"Réfection enduit façade","architecture":"classic Haussmann-style stone buildings with zinc rooftops and wrought-iron balconies","camera_position":"standing 2–4 m from the wall, straight-on or slight diagonal, eye level","contexte":"maison","exclude":["trowels","mixing tools","wheelbarrows","safety equipment","workers","people"],"framing":{"background":"adjacent existing structure or garden","foreground":"concrete blocks and mortar debris at the base, sand pile nearby","midground":"half-height wall under construction — fresh dark mortar joints clearly visible, blocks not yet fully set","work_pct":55},"light":"pale urban Île-de-France sky and diffuse city light","location":"Paris, France","no_people":true,"photo_defects":["flat midday light casting short even shadows","lens barrel distortion on straight wall lines"],"photo_goal":"work-progress documentation by French contractor, cheap Android smartphone","roadside_context":null,"setting":"exterior","site_debris":"mortar splashes on ground, block dust, open cement bags nearby","state":"The wall is at mid-height. Fresh mortar joints are visible. Blocks are stacked and ready. An active organised site.","state_level":"encours","work_type":"masonry work at a residential property"}',
    hash: 1460650968,
  },
];
